### ISSUE TITLE
Liquids (excluding tainted water) generate on the wall layer

### ISSUE THREAD

**Issue by kapzduke** [PiggyChu620/MindustryRandomPlanet#1]
![image](https://user-images.githubusercontent.com/60543005/230333632-301df6d1-7852-4dfd-b43b-08ab5dad1c84.png)
![image](https://user-images.githubusercontent.com/60543005/230333656-3c7cbf26-8035-4608-aca2-ed6460ec09cd.png)
![image](https://user-images.githubusercontent.com/60543005/230333678-998b738a-dfbf-4748-9a79-1e82fbddc705.png)

**Comment by PiggyChu620** [comment]
Thanks for your report, but imo as long as you could access it though a pump, it shouldn't be a problem, liquids other than shallow water can not be pumped except by the edges anyway.

**Comment by kapzduke** [comment]
persists
![image](https://user-images.githubusercontent.com/60543005/230917581-ae63f43f-338c-45b1-a148-511d458488dc.png)

**Comment by kapzduke** [comment]
i'm sure i updated

**Comment by kapzduke** [comment]
hey everybody, it's time for a game of "how long will it take for piggychu to fix this"

**Comment by PiggyChu620** [comment]
> hey everybody, it's time for a game of "how long will it take for piggychu to fix this"

I sincerely apologize for my negligence, I have been working on other projects for the past month or so, and I'll be out for a week, I'll be working on it right away when I get back, but before that, please tell me every bug, hopefully in details, you have encountered so far, much appreciated.

**Comment by PiggyChu620** [comment]
I finally fixed it, sorry for taking so long, please do let me know if you encounter any more bugs, thank you very much for your help!

**Comment by kapzduke** [comment]
thank you, liquids generate properly now, and sorry if i was mean

**Comment by PiggyChu620** [comment]
It's OK, it IS my fault that it took so long for me to fix it, and it's a
great honer for me that you're interested in my mod, please keep an eye out
on further bugs for me, thank you very much for your help.

kapzduke ***@***.***> 於 2023年7月5日 週三 上午9:39 寫道：

**Comment by PiggyChu620** [comment]
> thank you, liquids generate properly now, and sorry if i was mean

It's OK, it IS my fault that it took so long for me to fix it, and it's a great honer for me that you're interested in my mod, please keep an eye out on further bugs for me, thank you very much for your help.
