### ISSUE TITLE
Game crashes on Sector launch

### ISSUE THREAD

**Issue by UnknownDarkness** [PiggyChu620/MindustryRandomPlanet#2]
Hi, I am on Version 0.45.1 And whenever I try to launch to another sector after clearing the first, the game Crashes (EDIT: More Accurately, probably, the game goes into the loading screen indefinitely). At this point I believe I have exhausted all Permutations of Random Planet settings, so I really don't know what causes it.

I installed the mod from within Mindustry.

UPDATE: Got it to work by installing Mineable alloys after checking the Changelog. I would like to suggest changing the description to mention that Mod being a hard requirement. Sorry to bother you.

**Comment by PiggyChu620** [comment]
Thank you very much for your help, I'll go check my codes and see what makes Mineable Alloys a hard dependency.

**Comment by PiggyChu620** [comment]
Fixed, thank you very much for your bug report.
